import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Download, IndianRupee } from "lucide-react";
import { EmptyState, PageHeader } from "../components/shared";
import { useLocalAuth } from "../hooks/useLocalAuth";
import { useSalarySlipData } from "../hooks/useQueries";
import { formatINR } from "../utils/currencyUtils";

const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export default function SalarySlipPage() {
  const { user } = useLocalAuth();
  const staffId = user?.username ?? "";

  const { data: salaryData, isLoading } = useSalarySlipData(staffId);

  const handlePrint = () => {
    window.print();
  };

  const monthName = salaryData
    ? (MONTHS[Number(salaryData.month) - 1] ?? String(salaryData.month))
    : "";

  return (
    <div className="p-6 max-w-3xl mx-auto">
      <PageHeader
        title="Salary Slip"
        description="View and download your salary slip"
        actions={
          salaryData ? (
            <Button
              data-ocid="salary_slip.download.primary_button"
              onClick={handlePrint}
              className="no-print"
            >
              <Download className="h-4 w-4 mr-2" /> Download / Print
            </Button>
          ) : undefined
        }
      />

      {isLoading ? (
        <div className="space-y-4">
          <Skeleton className="h-48 rounded-lg" />
          <Skeleton className="h-32 rounded-lg" />
        </div>
      ) : !salaryData ? (
        <EmptyState
          title="No salary slip available"
          description="Your salary slip will appear here once payroll has been generated by your school admin."
          ocid="salary_slip.empty_state"
        />
      ) : (
        <div id="salary-slip-print">
          <Card className="shadow-card">
            {/* Header */}
            <CardHeader className="border-b border-border">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center">
                    <img
                      src="/assets/classio_logo_reel_compressed-019d539f-bf78-7716-bf0d-bb064308b5be.jpeg"
                      alt="Classio ERP"
                      className="w-10 h-10 rounded-lg object-cover"
                    />
                  </div>
                  <div>
                    <h2 className="font-bold text-lg text-foreground">
                      Classio ERP
                    </h2>
                    <p className="text-sm text-muted-foreground">
                      School Management System
                    </p>
                  </div>
                </div>
                <div className="text-right">
                  <p className="font-semibold text-foreground">SALARY SLIP</p>
                  <p className="text-sm text-muted-foreground">
                    {monthName} {Number(salaryData.year)}
                  </p>
                </div>
              </div>
            </CardHeader>

            <CardContent className="pt-6">
              {/* Employee Info */}
              <div className="grid grid-cols-2 gap-4 mb-6 p-4 rounded-lg bg-muted/30">
                <div>
                  <p className="text-xs text-muted-foreground">Employee ID</p>
                  <p className="font-mono text-sm font-medium mt-0.5">
                    {user?.username}
                  </p>
                </div>
                <div>
                  <p className="text-xs text-muted-foreground">Employee Name</p>
                  <p className="text-sm font-medium mt-0.5">{user?.name}</p>
                </div>
                <div>
                  <p className="text-xs text-muted-foreground">Pay Period</p>
                  <p className="text-sm font-medium mt-0.5">
                    {monthName} {Number(salaryData.year)}
                  </p>
                </div>
                <div>
                  <p className="text-xs text-muted-foreground">Role</p>
                  <p className="text-sm font-medium capitalize mt-0.5">
                    {user?.role}
                  </p>
                </div>
              </div>

              {/* Earnings & Deductions */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                {/* Earnings */}
                <div>
                  <h3 className="font-semibold text-sm text-foreground mb-3 flex items-center gap-2">
                    <IndianRupee className="h-4 w-4 text-success" />
                    Earnings
                  </h3>
                  <div className="space-y-2">
                    <div className="flex justify-between text-sm">
                      <span className="text-muted-foreground">
                        Basic Salary
                      </span>
                      <span className="font-medium">
                        {formatINR(salaryData.basicSalary)}
                      </span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span className="text-muted-foreground">Allowances</span>
                      <span className="font-medium text-success">
                        +{formatINR(salaryData.allowances)}
                      </span>
                    </div>
                    <div className="border-t border-border pt-2 flex justify-between text-sm font-semibold">
                      <span>Gross Salary</span>
                      <span>
                        {formatINR(
                          BigInt(
                            Number(salaryData.basicSalary) +
                              Number(salaryData.allowances),
                          ),
                        )}
                      </span>
                    </div>
                  </div>
                </div>

                {/* Deductions */}
                <div>
                  <h3 className="font-semibold text-sm text-foreground mb-3 flex items-center gap-2">
                    <IndianRupee className="h-4 w-4 text-destructive" />
                    Deductions
                  </h3>
                  <div className="space-y-2">
                    <div className="flex justify-between text-sm">
                      <span className="text-muted-foreground">
                        Total Deductions
                      </span>
                      <span className="font-medium text-destructive">
                        -{formatINR(salaryData.deductions)}
                      </span>
                    </div>
                    <div className="border-t border-border pt-2 flex justify-between text-sm font-semibold">
                      <span>Total Deducted</span>
                      <span className="text-destructive">
                        {formatINR(salaryData.deductions)}
                      </span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Net Salary */}
              <div className="rounded-xl bg-primary/10 border border-primary/20 p-5 flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">Net Salary</p>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    Gross Salary - Deductions
                  </p>
                </div>
                <div className="text-right">
                  <p className="text-2xl font-bold text-primary">
                    {formatINR(salaryData.netSalary)}
                  </p>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    For {monthName} {Number(salaryData.year)}
                  </p>
                </div>
              </div>

              <p className="text-xs text-muted-foreground text-center mt-4">
                This is a computer-generated salary slip. No signature required.
              </p>
            </CardContent>
          </Card>
        </div>
      )}

      <style>{`
        @media print {
          .no-print { display: none !important; }
          body { background: white; }
          #salary-slip-print { padding: 0; }
        }
      `}</style>
    </div>
  );
}
