import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { IndianRupee, Printer } from "lucide-react";
import { EmptyState, PageHeader } from "../components/shared";
import { useLocalAuth } from "../hooks/useLocalAuth";
import { useSalarySlipData } from "../hooks/useQueries";

const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

function formatAmt(n: number): string {
  return `₹${n.toLocaleString("en-IN")}`;
}

const DEFAULT_LOGO =
  "/assets/classio_logo_reel_compressed-019d539f-bf78-7716-bf0d-bb064308b5be.jpeg";

export default function SalarySlipPage() {
  const { user } = useLocalAuth();
  // Use the teacher's display name as staffId since payroll records are keyed by staff name
  const staffId = user?.name ?? user?.username ?? "";

  const { data: salaryData, isLoading } = useSalarySlipData(staffId);

  const schoolLogo =
    localStorage.getItem("classio_school_logo") || DEFAULT_LOGO;

  const handlePrint = () => {
    window.print();
  };

  const monthName = salaryData
    ? (MONTHS[Number(salaryData.month) - 1] ?? String(salaryData.month))
    : "";

  // Derive itemized breakdown from backend totals
  const basic = salaryData ? Number(salaryData.basicSalary) : 0;
  const storedAllowances = salaryData ? Number(salaryData.allowances) : 0;
  const storedDeductions = salaryData ? Number(salaryData.deductions) : 0;

  // Try to load stored breakdown from localStorage
  const getBreakdown = () => {
    if (!salaryData) return null;
    // Try specific month key first, then fall back to latest key
    const key = `payroll_breakdown_${salaryData.staffId}_${salaryData.month}_${salaryData.year}`;
    const latestKey = `payroll_breakdown_latest_${salaryData.staffId}`;
    const stored = localStorage.getItem(key) || localStorage.getItem(latestKey);
    if (stored) {
      try {
        return JSON.parse(stored) as {
          hra: number;
          conveyance: number;
          medical: number;
          specialAllowance: number;
          pf: number;
          tds: number;
          professionalTax: number;
          absentDays: number;
          absentDeduction: number;
          otherDeductions: number;
        };
      } catch {
        /* fall through */
      }
    }
    return null;
  };

  const stored = getBreakdown();

  const hra = stored ? stored.hra : Math.round(basic * 0.4);
  const conveyance = stored ? stored.conveyance : 1600;
  const medical = stored ? stored.medical : 1250;
  const specialAllowance = stored
    ? stored.specialAllowance
    : Math.max(0, storedAllowances - hra - conveyance - medical);

  const pf = stored ? stored.pf : Math.round(basic * 0.12);
  const professionalTax = stored ? stored.professionalTax : 200;
  const tdsAndOther = stored
    ? stored.tds
    : Math.max(0, storedDeductions - pf - professionalTax);
  const absentDeduction = stored ? stored.absentDeduction : 0;
  const otherDeductions = stored ? stored.otherDeductions : 0;

  const grossEarnings = basic + hra + conveyance + medical + specialAllowance;
  const totalDeductions =
    pf + tdsAndOther + professionalTax + absentDeduction + otherDeductions;
  const netPay = salaryData ? Number(salaryData.netSalary) : 0;

  return (
    <div className="p-6 max-w-3xl mx-auto">
      <PageHeader
        title="Salary Slip"
        description="View and download your salary slip"
        actions={
          salaryData ? (
            <Button
              data-ocid="salary_slip.download.primary_button"
              onClick={handlePrint}
              className="no-print"
            >
              <Printer className="h-4 w-4 mr-2" /> Print / Download
            </Button>
          ) : undefined
        }
      />

      {isLoading ? (
        <div className="space-y-4">
          <Skeleton className="h-48 rounded-lg" />
          <Skeleton className="h-32 rounded-lg" />
        </div>
      ) : !salaryData ? (
        <EmptyState
          title="No salary slip available"
          description="Your salary slip will appear here once payroll has been generated by your school admin."
          ocid="salary_slip.empty_state"
        />
      ) : (
        <div id="salary-slip-print">
          <Card className="shadow-card">
            {/* Slip Header */}
            <CardHeader className="border-b-2 border-primary pb-4">
              <div className="flex items-start justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center overflow-hidden">
                    <img
                      src={schoolLogo}
                      alt="Classio ERP"
                      className="w-11 h-11 rounded-lg object-cover"
                    />
                  </div>
                  <div>
                    <h2 className="font-bold text-xl text-foreground">
                      Classio ERP
                    </h2>
                    <p className="text-sm text-muted-foreground">
                      School Management System
                    </p>
                  </div>
                </div>
                <div className="text-right">
                  <p className="text-lg font-bold text-primary">SALARY SLIP</p>
                  <p className="text-sm text-muted-foreground">
                    {monthName} {Number(salaryData.year)}
                  </p>
                </div>
              </div>
            </CardHeader>

            <CardContent className="pt-5 space-y-5">
              {/* Employee Details */}
              <div className="grid grid-cols-2 gap-3 bg-muted/30 rounded-lg p-4">
                <div>
                  <p className="text-[10px] text-muted-foreground uppercase tracking-wide">
                    Employee Name
                  </p>
                  <p className="text-sm font-semibold mt-0.5">
                    {user?.name ?? user?.username}
                  </p>
                </div>
                <div>
                  <p className="text-[10px] text-muted-foreground uppercase tracking-wide">
                    Employee ID
                  </p>
                  <p className="font-mono text-sm font-medium mt-0.5">
                    {user?.username?.toUpperCase()}
                  </p>
                </div>
                <div>
                  <p className="text-[10px] text-muted-foreground uppercase tracking-wide">
                    Designation
                  </p>
                  <p className="text-sm font-medium capitalize mt-0.5">
                    {user?.role ?? "Teacher"}
                  </p>
                </div>
                <div>
                  <p className="text-[10px] text-muted-foreground uppercase tracking-wide">
                    Pay Period
                  </p>
                  <p className="text-sm font-medium mt-0.5">
                    {monthName} {Number(salaryData.year)}
                  </p>
                </div>
              </div>

              {/* Earnings & Deductions — side-by-side on md+ */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Earnings */}
                <div className="border border-border rounded-lg overflow-hidden">
                  <div className="bg-emerald-50 border-b border-border px-3 py-2 flex items-center gap-1.5">
                    <IndianRupee className="h-3.5 w-3.5 text-emerald-700" />
                    <h3 className="text-xs font-bold uppercase tracking-wider text-emerald-700">
                      Earnings
                    </h3>
                  </div>
                  <div className="divide-y divide-border">
                    {[
                      ["Basic Salary", basic],
                      ["HRA", hra],
                      ["Conveyance Allowance", conveyance],
                      ["Medical Allowance", medical],
                      ["Special Allowance", specialAllowance],
                    ].map(([label, amount]) => (
                      <div
                        key={String(label)}
                        className="flex justify-between px-3 py-2 text-sm"
                      >
                        <span className="text-muted-foreground">{label}</span>
                        <span className="font-medium text-emerald-700">
                          {formatAmt(Number(amount))}
                        </span>
                      </div>
                    ))}
                    <div className="flex justify-between px-3 py-2.5 text-sm bg-emerald-50/60">
                      <span className="font-bold text-emerald-800">
                        Gross Earnings
                      </span>
                      <span className="font-bold text-emerald-800">
                        {formatAmt(grossEarnings)}
                      </span>
                    </div>
                  </div>
                </div>

                {/* Deductions */}
                <div className="border border-border rounded-lg overflow-hidden">
                  <div className="bg-red-50 border-b border-border px-3 py-2 flex items-center gap-1.5">
                    <IndianRupee className="h-3.5 w-3.5 text-red-700" />
                    <h3 className="text-xs font-bold uppercase tracking-wider text-red-700">
                      Deductions
                    </h3>
                  </div>
                  <div className="divide-y divide-border">
                    {[
                      ["Provident Fund (PF)", pf],
                      ["TDS / Income Tax", tdsAndOther],
                      ["Professional Tax", professionalTax],
                      ["Absent Day Deduction", absentDeduction],
                      ["Other Deductions", otherDeductions],
                    ].map(([label, amount]) => (
                      <div
                        key={String(label)}
                        className="flex justify-between px-3 py-2 text-sm"
                      >
                        <span className="text-muted-foreground">{label}</span>
                        <span className="font-medium text-red-600">
                          {formatAmt(Number(amount))}
                        </span>
                      </div>
                    ))}
                    <div className="flex justify-between px-3 py-2.5 text-sm bg-red-50/60">
                      <span className="font-bold text-red-800">
                        Total Deductions
                      </span>
                      <span className="font-bold text-red-800">
                        {formatAmt(totalDeductions)}
                      </span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Net Pay */}
              <div className="rounded-xl bg-primary/10 border border-primary/30 p-5 flex items-center justify-between">
                <div>
                  <p className="text-sm font-bold text-primary">NET PAY</p>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    Gross Earnings − Total Deductions
                  </p>
                </div>
                <div className="text-right">
                  <p className="text-3xl font-bold text-primary">
                    {formatAmt(netPay)}
                  </p>
                  <p className="text-xs text-muted-foreground mt-1">
                    For {monthName} {Number(salaryData.year)}
                  </p>
                </div>
              </div>

              <p className="text-xs text-muted-foreground text-center border-t border-dashed border-border pt-3">
                This is a computer-generated salary slip. No signature required.
              </p>
            </CardContent>
          </Card>
        </div>
      )}

      <style>{`
        @media print {
          .no-print { display: none !important; }
          body { background: white; }
          #salary-slip-print { padding: 0; }
        }
      `}</style>
    </div>
  );
}
