/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CourseId = IDL.Text;
export const Title = IDL.Text;
export const Instructions = IDL.Text;
export const DueDate = IDL.Int;
export const MaxScore = IDL.Nat;
export const Identifier = IDL.Text;
export const ContentText = IDL.Text;
export const OrderIndex = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Body = IDL.Text;
export const AuthorName = IDL.Text;
export const Name = IDL.Text;
export const Subjects = IDL.Vec(IDL.Text);
export const Position = IDL.Text;
export const DepartmentId = IDL.Text;
export const EmploymentType = IDL.Text;
export const Salary = IDL.Nat;
export const ContactEmail = IDL.Text;
export const ContactPhone = IDL.Text;
export const HireDate = IDL.Int;
export const IsActive = IDL.Bool;
export const Grade = IDL.Nat;
export const ParentName = IDL.Text;
export const EnrollmentDate = IDL.Int;
export const DateOfJoin = IDL.Int;
export const Course = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'description' : IDL.Text,
  'classId' : IDL.Text,
  'isActive' : IDL.Bool,
  'teacherId' : IDL.Text,
});
export const Staff = IDL.Record({
  'id' : Identifier,
  'salary' : Salary,
  'hireDate' : HireDate,
  'isActive' : IsActive,
  'employmentType' : EmploymentType,
  'contactEmail' : ContactEmail,
  'position' : Position,
  'lastName' : IDL.Text,
  'departmentId' : DepartmentId,
  'contactPhone' : ContactPhone,
  'firstName' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : Identifier,
  'isActive' : IsActive,
  'grade' : Grade,
  'contactEmail' : ContactEmail,
  'enrollmentDate' : EnrollmentDate,
  'lastName' : IDL.Text,
  'parentName' : ParentName,
  'contactPhone' : ContactPhone,
  'firstName' : IDL.Text,
});
export const Teacher = IDL.Record({
  'id' : Identifier,
  'subjects' : Subjects,
  'isActive' : IsActive,
  'contactEmail' : ContactEmail,
  'lastName' : IDL.Text,
  'dateOfJoin' : DateOfJoin,
  'contactPhone' : ContactPhone,
  'firstName' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const Announcement = IDL.Record({
  'id' : IDL.Text,
  'title' : Title,
  'body' : Body,
  'authorName' : AuthorName,
  'timestamp' : Timestamp,
});
export const Class = IDL.Record({
  'id' : Identifier,
  'subjects' : Subjects,
  'name' : Name,
  'teacherId' : Identifier,
});
export const Department = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const ResourceLink = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'resourceType' : IDL.Text,
  'courseId' : IDL.Text,
});
export const Assignment = IDL.Record({
  'id' : Identifier,
  'title' : Title,
  'maxScore' : MaxScore,
  'dueDate' : DueDate,
  'instructions' : Instructions,
  'courseId' : CourseId,
});
export const AttendanceRecord = IDL.Record({
  'absentStudents' : IDL.Vec(Identifier),
  'date' : IDL.Int,
  'classId' : Identifier,
  'presentStudents' : IDL.Vec(Identifier),
});
export const UserProfile = IDL.Record({
  'linkedId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const Subject = IDL.Text;
export const Term = IDL.Text;
export const Score = IDL.Nat;
export const Remarks = IDL.Text;
export const GradeRecord = IDL.Record({
  'studentId' : Identifier,
  'subject' : Subject,
  'term' : Term,
  'score' : Score,
  'remarks' : Remarks,
});
export const Status = IDL.Text;
export const EndDate = IDL.Int;
export const StaffId = IDL.Text;
export const LeaveType = IDL.Text;
export const StartDate = IDL.Int;
export const Reason = IDL.Text;
export const LeaveRequest = IDL.Record({
  'id' : Identifier,
  'status' : Status,
  'endDate' : EndDate,
  'staffId' : StaffId,
  'leaveType' : LeaveType,
  'startDate' : StartDate,
  'reason' : Reason,
});
export const Lesson = IDL.Record({
  'id' : Identifier,
  'title' : Title,
  'contentText' : ContentText,
  'courseId' : CourseId,
  'orderIndex' : OrderIndex,
});
export const PayrollRecord = IDL.Record({
  'id' : IDL.Text,
  'month' : IDL.Nat,
  'staffId' : IDL.Text,
  'year' : IDL.Nat,
  'deductions' : IDL.Nat,
  'isPaid' : IDL.Bool,
  'netPay' : IDL.Nat,
  'allowances' : IDL.Nat,
  'basicSalary' : IDL.Nat,
});
export const SchoolProfile = IDL.Record({
  'motto' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'schoolName' : IDL.Text,
});
export const AssignmentSubmission = IDL.Record({
  'id' : IDL.Text,
  'studentId' : Identifier,
  'submittedAt' : IDL.Int,
  'feedback' : IDL.Opt(IDL.Text),
  'isGraded' : IDL.Bool,
  'score' : IDL.Opt(IDL.Nat),
  'assignmentId' : Identifier,
  'submissionText' : IDL.Text,
});
export const AttendanceRecordInput = IDL.Record({
  'absentStudents' : IDL.Vec(Identifier),
  'date' : IDL.Int,
  'classId' : Identifier,
  'presentStudents' : IDL.Vec(Identifier),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateAssignment' : IDL.Func(
      [CourseId, Title, Instructions, DueDate, MaxScore],
      [Identifier],
      [],
    ),
  'addOrUpdateCourse' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Text],
      [],
    ),
  'addOrUpdateDepartment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addOrUpdateLesson' : IDL.Func(
      [CourseId, Title, ContentText, OrderIndex],
      [Identifier],
      [],
    ),
  'addResourceLink' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'approveLeaveRequest' : IDL.Func([Identifier], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnnouncement' : IDL.Func([Title, Body, AuthorName], [IDL.Text], []),
  'createClass' : IDL.Func([Name, Identifier, Subjects], [Identifier], []),
  'createStaff' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Position,
        DepartmentId,
        EmploymentType,
        Salary,
        ContactEmail,
        ContactPhone,
        HireDate,
        IsActive,
      ],
      [Identifier],
      [],
    ),
  'createStudent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Grade,
        ContactEmail,
        ContactPhone,
        ParentName,
        EnrollmentDate,
        IsActive,
      ],
      [Identifier],
      [],
    ),
  'createTeacher' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Subjects,
        ContactEmail,
        ContactPhone,
        DateOfJoin,
        IsActive,
      ],
      [Identifier],
      [],
    ),
  'deleteClass' : IDL.Func([Identifier], [], []),
  'deleteCourse' : IDL.Func([IDL.Text], [], []),
  'deleteDepartment' : IDL.Func([IDL.Text], [], []),
  'deleteStaff' : IDL.Func([Identifier], [], []),
  'deleteStudent' : IDL.Func([Identifier], [], []),
  'deleteTeacher' : IDL.Func([Identifier], [], []),
  'enrollStudentInClass' : IDL.Func([Identifier, IDL.Opt(Identifier)], [], []),
  'generatePayroll' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'getActiveLMSCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getActiveStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
  'getActiveStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getActiveTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
  'getAllResourceLinks' : IDL.Func([], [IDL.Vec(ResourceLink)], ['query']),
  'getAllStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
  'getAnnouncement' : IDL.Func([IDL.Text], [Announcement], ['query']),
  'getAssignment' : IDL.Func([Identifier], [Assignment], ['query']),
  'getAssignmentsByCourse' : IDL.Func(
      [CourseId],
      [IDL.Vec(Assignment)],
      ['query'],
    ),
  'getAttendance' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByClassAndDate' : IDL.Func(
      [Identifier, IDL.Int],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClass' : IDL.Func([Identifier], [Class], ['query']),
  'getCourse' : IDL.Func([IDL.Text], [Course], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalClasses' : IDL.Nat,
          'totalStudents' : IDL.Nat,
          'totalStaff' : IDL.Nat,
          'totalTeachers' : IDL.Nat,
          'totalCourses' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getDepartment' : IDL.Func([IDL.Text], [Department], ['query']),
  'getGrade' : IDL.Func([IDL.Text], [GradeRecord], ['query']),
  'getGradesByStudent' : IDL.Func(
      [Identifier],
      [IDL.Vec(GradeRecord)],
      ['query'],
    ),
  'getGradesBySubject' : IDL.Func([Subject], [IDL.Vec(GradeRecord)], ['query']),
  'getLeaveRequest' : IDL.Func([Identifier], [LeaveRequest], ['query']),
  'getLeaveRequestsByStaff' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LeaveRequest)],
      ['query'],
    ),
  'getLesson' : IDL.Func([Identifier], [Lesson], ['query']),
  'getLessonsByCourse' : IDL.Func([CourseId], [IDL.Vec(Lesson)], ['query']),
  'getPayrollRecord' : IDL.Func([IDL.Text], [PayrollRecord], ['query']),
  'getPayrollRecordsByStaff' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PayrollRecord)],
      ['query'],
    ),
  'getPendingLeaveRequests' : IDL.Func([], [IDL.Vec(LeaveRequest)], ['query']),
  'getResourceLinksByCourse' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ResourceLink)],
      ['query'],
    ),
  'getSchoolProfile' : IDL.Func([], [SchoolProfile], ['query']),
  'getStaff' : IDL.Func([Identifier], [Staff], ['query']),
  'getStudent' : IDL.Func([Identifier], [Student], ['query']),
  'getStudentsSortedByFirstName' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getStudentsSortedByLastName' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getSubmission' : IDL.Func([IDL.Text], [AssignmentSubmission], ['query']),
  'getSubmissionsByAssignment' : IDL.Func(
      [Identifier],
      [IDL.Vec(AssignmentSubmission)],
      ['query'],
    ),
  'getSubmissionsByStudent' : IDL.Func(
      [Identifier],
      [IDL.Vec(AssignmentSubmission)],
      ['query'],
    ),
  'getTeacher' : IDL.Func([Identifier], [Teacher], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'gradeSubmission' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markPayrollAsPaid' : IDL.Func([IDL.Text], [], []),
  'recordAttendance' : IDL.Func([AttendanceRecordInput], [IDL.Text], []),
  'recordGrade' : IDL.Func(
      [Identifier, Subject, Term, Score, Remarks],
      [IDL.Text],
      [],
    ),
  'rejectLeaveRequest' : IDL.Func([Identifier], [], []),
  'removeStudentFromClass' : IDL.Func([Identifier, Identifier], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAssignment' : IDL.Func(
      [Identifier, Identifier, IDL.Text],
      [IDL.Text],
      [],
    ),
  'submitLeaveRequest' : IDL.Func(
      [StaffId, LeaveType, StartDate, EndDate, Reason],
      [Identifier],
      [],
    ),
  'updateClass' : IDL.Func(
      [Identifier, Name, Identifier, Subjects],
      [Identifier],
      [],
    ),
  'updateStaff' : IDL.Func(
      [
        Identifier,
        IDL.Text,
        IDL.Text,
        Position,
        DepartmentId,
        EmploymentType,
        Salary,
        ContactEmail,
        ContactPhone,
        HireDate,
        IsActive,
      ],
      [Identifier],
      [],
    ),
  'updateStudent' : IDL.Func(
      [
        Identifier,
        IDL.Text,
        IDL.Text,
        Grade,
        ContactEmail,
        ContactPhone,
        ParentName,
        EnrollmentDate,
        IsActive,
      ],
      [Identifier],
      [],
    ),
  'updateTeacher' : IDL.Func(
      [
        Identifier,
        IDL.Text,
        IDL.Text,
        Subjects,
        ContactEmail,
        ContactPhone,
        DateOfJoin,
        IsActive,
      ],
      [Identifier],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CourseId = IDL.Text;
  const Title = IDL.Text;
  const Instructions = IDL.Text;
  const DueDate = IDL.Int;
  const MaxScore = IDL.Nat;
  const Identifier = IDL.Text;
  const ContentText = IDL.Text;
  const OrderIndex = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Body = IDL.Text;
  const AuthorName = IDL.Text;
  const Name = IDL.Text;
  const Subjects = IDL.Vec(IDL.Text);
  const Position = IDL.Text;
  const DepartmentId = IDL.Text;
  const EmploymentType = IDL.Text;
  const Salary = IDL.Nat;
  const ContactEmail = IDL.Text;
  const ContactPhone = IDL.Text;
  const HireDate = IDL.Int;
  const IsActive = IDL.Bool;
  const Grade = IDL.Nat;
  const ParentName = IDL.Text;
  const EnrollmentDate = IDL.Int;
  const DateOfJoin = IDL.Int;
  const Course = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'description' : IDL.Text,
    'classId' : IDL.Text,
    'isActive' : IDL.Bool,
    'teacherId' : IDL.Text,
  });
  const Staff = IDL.Record({
    'id' : Identifier,
    'salary' : Salary,
    'hireDate' : HireDate,
    'isActive' : IsActive,
    'employmentType' : EmploymentType,
    'contactEmail' : ContactEmail,
    'position' : Position,
    'lastName' : IDL.Text,
    'departmentId' : DepartmentId,
    'contactPhone' : ContactPhone,
    'firstName' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : Identifier,
    'isActive' : IsActive,
    'grade' : Grade,
    'contactEmail' : ContactEmail,
    'enrollmentDate' : EnrollmentDate,
    'lastName' : IDL.Text,
    'parentName' : ParentName,
    'contactPhone' : ContactPhone,
    'firstName' : IDL.Text,
  });
  const Teacher = IDL.Record({
    'id' : Identifier,
    'subjects' : Subjects,
    'isActive' : IsActive,
    'contactEmail' : ContactEmail,
    'lastName' : IDL.Text,
    'dateOfJoin' : DateOfJoin,
    'contactPhone' : ContactPhone,
    'firstName' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const Announcement = IDL.Record({
    'id' : IDL.Text,
    'title' : Title,
    'body' : Body,
    'authorName' : AuthorName,
    'timestamp' : Timestamp,
  });
  const Class = IDL.Record({
    'id' : Identifier,
    'subjects' : Subjects,
    'name' : Name,
    'teacherId' : Identifier,
  });
  const Department = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const ResourceLink = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'resourceType' : IDL.Text,
    'courseId' : IDL.Text,
  });
  const Assignment = IDL.Record({
    'id' : Identifier,
    'title' : Title,
    'maxScore' : MaxScore,
    'dueDate' : DueDate,
    'instructions' : Instructions,
    'courseId' : CourseId,
  });
  const AttendanceRecord = IDL.Record({
    'absentStudents' : IDL.Vec(Identifier),
    'date' : IDL.Int,
    'classId' : Identifier,
    'presentStudents' : IDL.Vec(Identifier),
  });
  const UserProfile = IDL.Record({
    'linkedId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const Subject = IDL.Text;
  const Term = IDL.Text;
  const Score = IDL.Nat;
  const Remarks = IDL.Text;
  const GradeRecord = IDL.Record({
    'studentId' : Identifier,
    'subject' : Subject,
    'term' : Term,
    'score' : Score,
    'remarks' : Remarks,
  });
  const Status = IDL.Text;
  const EndDate = IDL.Int;
  const StaffId = IDL.Text;
  const LeaveType = IDL.Text;
  const StartDate = IDL.Int;
  const Reason = IDL.Text;
  const LeaveRequest = IDL.Record({
    'id' : Identifier,
    'status' : Status,
    'endDate' : EndDate,
    'staffId' : StaffId,
    'leaveType' : LeaveType,
    'startDate' : StartDate,
    'reason' : Reason,
  });
  const Lesson = IDL.Record({
    'id' : Identifier,
    'title' : Title,
    'contentText' : ContentText,
    'courseId' : CourseId,
    'orderIndex' : OrderIndex,
  });
  const PayrollRecord = IDL.Record({
    'id' : IDL.Text,
    'month' : IDL.Nat,
    'staffId' : IDL.Text,
    'year' : IDL.Nat,
    'deductions' : IDL.Nat,
    'isPaid' : IDL.Bool,
    'netPay' : IDL.Nat,
    'allowances' : IDL.Nat,
    'basicSalary' : IDL.Nat,
  });
  const SchoolProfile = IDL.Record({
    'motto' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'schoolName' : IDL.Text,
  });
  const AssignmentSubmission = IDL.Record({
    'id' : IDL.Text,
    'studentId' : Identifier,
    'submittedAt' : IDL.Int,
    'feedback' : IDL.Opt(IDL.Text),
    'isGraded' : IDL.Bool,
    'score' : IDL.Opt(IDL.Nat),
    'assignmentId' : Identifier,
    'submissionText' : IDL.Text,
  });
  const AttendanceRecordInput = IDL.Record({
    'absentStudents' : IDL.Vec(Identifier),
    'date' : IDL.Int,
    'classId' : Identifier,
    'presentStudents' : IDL.Vec(Identifier),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateAssignment' : IDL.Func(
        [CourseId, Title, Instructions, DueDate, MaxScore],
        [Identifier],
        [],
      ),
    'addOrUpdateCourse' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Text],
        [],
      ),
    'addOrUpdateDepartment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addOrUpdateLesson' : IDL.Func(
        [CourseId, Title, ContentText, OrderIndex],
        [Identifier],
        [],
      ),
    'addResourceLink' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'approveLeaveRequest' : IDL.Func([Identifier], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnnouncement' : IDL.Func([Title, Body, AuthorName], [IDL.Text], []),
    'createClass' : IDL.Func([Name, Identifier, Subjects], [Identifier], []),
    'createStaff' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Position,
          DepartmentId,
          EmploymentType,
          Salary,
          ContactEmail,
          ContactPhone,
          HireDate,
          IsActive,
        ],
        [Identifier],
        [],
      ),
    'createStudent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Grade,
          ContactEmail,
          ContactPhone,
          ParentName,
          EnrollmentDate,
          IsActive,
        ],
        [Identifier],
        [],
      ),
    'createTeacher' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Subjects,
          ContactEmail,
          ContactPhone,
          DateOfJoin,
          IsActive,
        ],
        [Identifier],
        [],
      ),
    'deleteClass' : IDL.Func([Identifier], [], []),
    'deleteCourse' : IDL.Func([IDL.Text], [], []),
    'deleteDepartment' : IDL.Func([IDL.Text], [], []),
    'deleteStaff' : IDL.Func([Identifier], [], []),
    'deleteStudent' : IDL.Func([Identifier], [], []),
    'deleteTeacher' : IDL.Func([Identifier], [], []),
    'enrollStudentInClass' : IDL.Func(
        [Identifier, IDL.Opt(Identifier)],
        [],
        [],
      ),
    'generatePayroll' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'getActiveLMSCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getActiveStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
    'getActiveStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getActiveTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
    'getAllResourceLinks' : IDL.Func([], [IDL.Vec(ResourceLink)], ['query']),
    'getAllStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
    'getAnnouncement' : IDL.Func([IDL.Text], [Announcement], ['query']),
    'getAssignment' : IDL.Func([Identifier], [Assignment], ['query']),
    'getAssignmentsByCourse' : IDL.Func(
        [CourseId],
        [IDL.Vec(Assignment)],
        ['query'],
      ),
    'getAttendance' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByClassAndDate' : IDL.Func(
        [Identifier, IDL.Int],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClass' : IDL.Func([Identifier], [Class], ['query']),
    'getCourse' : IDL.Func([IDL.Text], [Course], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalClasses' : IDL.Nat,
            'totalStudents' : IDL.Nat,
            'totalStaff' : IDL.Nat,
            'totalTeachers' : IDL.Nat,
            'totalCourses' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getDepartment' : IDL.Func([IDL.Text], [Department], ['query']),
    'getGrade' : IDL.Func([IDL.Text], [GradeRecord], ['query']),
    'getGradesByStudent' : IDL.Func(
        [Identifier],
        [IDL.Vec(GradeRecord)],
        ['query'],
      ),
    'getGradesBySubject' : IDL.Func(
        [Subject],
        [IDL.Vec(GradeRecord)],
        ['query'],
      ),
    'getLeaveRequest' : IDL.Func([Identifier], [LeaveRequest], ['query']),
    'getLeaveRequestsByStaff' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LeaveRequest)],
        ['query'],
      ),
    'getLesson' : IDL.Func([Identifier], [Lesson], ['query']),
    'getLessonsByCourse' : IDL.Func([CourseId], [IDL.Vec(Lesson)], ['query']),
    'getPayrollRecord' : IDL.Func([IDL.Text], [PayrollRecord], ['query']),
    'getPayrollRecordsByStaff' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PayrollRecord)],
        ['query'],
      ),
    'getPendingLeaveRequests' : IDL.Func(
        [],
        [IDL.Vec(LeaveRequest)],
        ['query'],
      ),
    'getResourceLinksByCourse' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ResourceLink)],
        ['query'],
      ),
    'getSchoolProfile' : IDL.Func([], [SchoolProfile], ['query']),
    'getStaff' : IDL.Func([Identifier], [Staff], ['query']),
    'getStudent' : IDL.Func([Identifier], [Student], ['query']),
    'getStudentsSortedByFirstName' : IDL.Func(
        [],
        [IDL.Vec(Student)],
        ['query'],
      ),
    'getStudentsSortedByLastName' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getSubmission' : IDL.Func([IDL.Text], [AssignmentSubmission], ['query']),
    'getSubmissionsByAssignment' : IDL.Func(
        [Identifier],
        [IDL.Vec(AssignmentSubmission)],
        ['query'],
      ),
    'getSubmissionsByStudent' : IDL.Func(
        [Identifier],
        [IDL.Vec(AssignmentSubmission)],
        ['query'],
      ),
    'getTeacher' : IDL.Func([Identifier], [Teacher], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'gradeSubmission' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markPayrollAsPaid' : IDL.Func([IDL.Text], [], []),
    'recordAttendance' : IDL.Func([AttendanceRecordInput], [IDL.Text], []),
    'recordGrade' : IDL.Func(
        [Identifier, Subject, Term, Score, Remarks],
        [IDL.Text],
        [],
      ),
    'rejectLeaveRequest' : IDL.Func([Identifier], [], []),
    'removeStudentFromClass' : IDL.Func([Identifier, Identifier], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAssignment' : IDL.Func(
        [Identifier, Identifier, IDL.Text],
        [IDL.Text],
        [],
      ),
    'submitLeaveRequest' : IDL.Func(
        [StaffId, LeaveType, StartDate, EndDate, Reason],
        [Identifier],
        [],
      ),
    'updateClass' : IDL.Func(
        [Identifier, Name, Identifier, Subjects],
        [Identifier],
        [],
      ),
    'updateStaff' : IDL.Func(
        [
          Identifier,
          IDL.Text,
          IDL.Text,
          Position,
          DepartmentId,
          EmploymentType,
          Salary,
          ContactEmail,
          ContactPhone,
          HireDate,
          IsActive,
        ],
        [Identifier],
        [],
      ),
    'updateStudent' : IDL.Func(
        [
          Identifier,
          IDL.Text,
          IDL.Text,
          Grade,
          ContactEmail,
          ContactPhone,
          ParentName,
          EnrollmentDate,
          IsActive,
        ],
        [Identifier],
        [],
      ),
    'updateTeacher' : IDL.Func(
        [
          Identifier,
          IDL.Text,
          IDL.Text,
          Subjects,
          ContactEmail,
          ContactPhone,
          DateOfJoin,
          IsActive,
        ],
        [Identifier],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };