/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : string,
  'title' : Title,
  'body' : Body,
  'authorName' : AuthorName,
  'timestamp' : Timestamp,
}
export interface Applicant {
  'id' : ApplicantId,
  'status' : string,
  'classApplied' : string,
  'email' : string,
  'dateApplied' : bigint,
  'programApplied' : string,
  'notes' : Notes,
  'phone' : string,
  'lastName' : string,
  'firstName' : string,
}
export type ApplicantId = string;
export interface Assignment {
  'id' : Identifier,
  'title' : Title,
  'maxScore' : MaxScore,
  'dueDate' : DueDate,
  'instructions' : Instructions,
  'courseId' : CourseId,
}
export interface AssignmentSubmission {
  'id' : string,
  'studentId' : Identifier,
  'submittedAt' : bigint,
  'feedback' : [] | [string],
  'isGraded' : boolean,
  'score' : [] | [bigint],
  'assignmentId' : Identifier,
  'submissionText' : string,
}
export interface AttendanceCorrection {
  'id' : string,
  'status' : string,
  'staffId' : string,
  'date' : bigint,
  'requestedStatus' : string,
  'reason' : string,
}
export interface AttendanceRecord {
  'absentStudents' : Array<Identifier>,
  'date' : bigint,
  'classId' : Identifier,
  'presentStudents' : Array<Identifier>,
}
export interface AttendanceRecordInput {
  'absentStudents' : Array<Identifier>,
  'date' : bigint,
  'classId' : Identifier,
  'presentStudents' : Array<Identifier>,
}
export type AuthorName = string;
export type Body = string;
export interface Class {
  'id' : Identifier,
  'subjects' : Subjects,
  'name' : Name,
  'teacherId' : Identifier,
}
export type ContactEmail = string;
export type ContactPhone = string;
export type ContentText = string;
export interface Course {
  'id' : string,
  'title' : string,
  'subject' : string,
  'description' : string,
  'classId' : string,
  'isActive' : boolean,
  'teacherId' : string,
}
export type CourseId = string;
export type DateOfJoin = bigint;
export interface Department {
  'id' : string,
  'name' : string,
  'description' : string,
}
export type DepartmentId = string;
export type DueDate = bigint;
export type EmploymentType = string;
export type EndDate = bigint;
export type EnrollmentDate = bigint;
export interface Expense {
  'id' : string,
  'date' : bigint,
  'approvedBy' : string,
  'description' : string,
  'category' : string,
  'amount' : bigint,
}
export type FeeId = string;
export interface FeeStructure {
  'id' : FeeId,
  'name' : string,
  'feeType' : string,
  'description' : string,
  'isActive' : IsActive,
  'academicYear' : string,
  'gradeLevel' : GradeLevel,
  'feeTypeLabel' : string,
  'amount' : bigint,
}
export type Grade = bigint;
export type GradeLevel = string;
export interface GradeRecord {
  'studentId' : Identifier,
  'subject' : Subject,
  'term' : Term,
  'score' : Score,
  'remarks' : Remarks,
}
export type HireDate = bigint;
export type Identifier = string;
export type Instructions = string;
export type IsActive = boolean;
export interface LeaveRequest {
  'id' : Identifier,
  'status' : Status,
  'endDate' : EndDate,
  'staffId' : StaffId,
  'leaveType' : LeaveType,
  'startDate' : StartDate,
  'reason' : Reason,
}
export type LeaveType = string;
export interface Lesson {
  'id' : Identifier,
  'title' : Title,
  'contentText' : ContentText,
  'courseId' : CourseId,
  'orderIndex' : OrderIndex,
}
export type MaxScore = bigint;
export type Name = string;
export type Notes = string;
export type OrderIndex = bigint;
export type ParentName = string;
export interface Payment {
  'id' : string,
  'method' : string,
  'studentId' : Identifier,
  'invoiceId' : string,
  'notes' : string,
  'paymentDate' : bigint,
  'amount' : bigint,
}
export interface PayrollRecord {
  'id' : string,
  'month' : bigint,
  'staffId' : string,
  'year' : bigint,
  'deductions' : bigint,
  'isPaid' : boolean,
  'netPay' : bigint,
  'allowances' : bigint,
  'basicSalary' : bigint,
}
export type Position = string;
export type Reason = string;
export type Remarks = string;
export interface ResourceLink {
  'id' : string,
  'url' : string,
  'title' : string,
  'resourceType' : string,
  'courseId' : string,
}
export type Salary = bigint;
export interface SalarySlipData {
  'month' : bigint,
  'staffId' : string,
  'year' : bigint,
  'deductions' : bigint,
  'netSalary' : bigint,
  'allowances' : bigint,
  'basicSalary' : bigint,
}
export interface SchoolProfile {
  'motto' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
  'schoolName' : string,
}
export type Score = bigint;
export interface Staff {
  'id' : Identifier,
  'salary' : Salary,
  'hireDate' : HireDate,
  'isActive' : IsActive,
  'employmentType' : EmploymentType,
  'contactEmail' : ContactEmail,
  'position' : Position,
  'lastName' : string,
  'departmentId' : DepartmentId,
  'contactPhone' : ContactPhone,
  'firstName' : string,
}
export type StaffId = string;
export type StartDate = bigint;
export type Status = string;
export interface Student {
  'id' : Identifier,
  'dob' : [] | [bigint],
  'isActive' : IsActive,
  'grade' : Grade,
  'contactEmail' : ContactEmail,
  'enrollmentDate' : EnrollmentDate,
  'lastName' : string,
  'parentName' : ParentName,
  'contactPhone' : ContactPhone,
  'firstName' : string,
}
export interface StudentInvoice {
  'id' : string,
  'status' : string,
  'studentId' : Identifier,
  'feeStructureId' : string,
  'dueDate' : bigint,
  'issuedDate' : bigint,
  'amount' : bigint,
}
export type Subject = string;
export type Subjects = Array<string>;
export interface Teacher {
  'id' : Identifier,
  'subjects' : Subjects,
  'isActive' : IsActive,
  'grade' : [] | [string],
  'contactEmail' : ContactEmail,
  'lastName' : string,
  'dateOfJoin' : DateOfJoin,
  'contactPhone' : ContactPhone,
  'firstName' : string,
}
export interface TeacherAttendance {
  'id' : string,
  'status' : string,
  'date' : bigint,
  'notes' : string,
  'teacherId' : string,
}
export type Term = string;
export type Timestamp = bigint;
export type Title = string;
export interface UserProfile {
  'linkedId' : [] | [string],
  'name' : string,
  'role' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateAssignment' : ActorMethod<
    [CourseId, Title, Instructions, DueDate, MaxScore],
    Identifier
  >,
  'addOrUpdateCourse' : ActorMethod<
    [string, string, string, string, string, boolean],
    string
  >,
  'addOrUpdateDepartment' : ActorMethod<[string, string, string], string>,
  'addOrUpdateLesson' : ActorMethod<
    [CourseId, Title, ContentText, OrderIndex],
    Identifier
  >,
  'addResourceLink' : ActorMethod<[string, string, string, string], string>,
  'addTeacherAttendance' : ActorMethod<
    [string, bigint, string, string],
    string
  >,
  'approveAttendanceCorrection' : ActorMethod<[string], undefined>,
  'approveLeaveRequest' : ActorMethod<[Identifier], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'convertApplicantToStudent' : ActorMethod<[string], Identifier>,
  'createAnnouncement' : ActorMethod<[Title, Body, AuthorName], string>,
  'createApplicant' : ActorMethod<
    [string, string, string, string, string, string, bigint, string, Notes],
    string
  >,
  'createClass' : ActorMethod<[Name, Identifier, Subjects], Identifier>,
  'createExpense' : ActorMethod<
    [string, string, bigint, bigint, string],
    string
  >,
  'createFeeStructure' : ActorMethod<
    [string, string, bigint, GradeLevel, string, string, string, IsActive],
    string
  >,
  'createPayment' : ActorMethod<
    [string, Identifier, bigint, bigint, string, string],
    string
  >,
  'createStaff' : ActorMethod<
    [
      string,
      string,
      Position,
      DepartmentId,
      EmploymentType,
      Salary,
      ContactEmail,
      ContactPhone,
      HireDate,
      IsActive,
    ],
    Identifier
  >,
  'createStudent' : ActorMethod<
    [
      string,
      string,
      Grade,
      ContactEmail,
      ContactPhone,
      ParentName,
      EnrollmentDate,
      [] | [bigint],
      IsActive,
    ],
    Identifier
  >,
  'createStudentInvoice' : ActorMethod<
    [Identifier, string, bigint, bigint, string, bigint],
    string
  >,
  'createTeacher' : ActorMethod<
    [
      string,
      string,
      Subjects,
      ContactEmail,
      ContactPhone,
      DateOfJoin,
      [] | [string],
      IsActive,
    ],
    Identifier
  >,
  'deleteApplicant' : ActorMethod<[string], undefined>,
  'deleteClass' : ActorMethod<[Identifier], undefined>,
  'deleteCourse' : ActorMethod<[string], undefined>,
  'deleteDepartment' : ActorMethod<[string], undefined>,
  'deleteExpense' : ActorMethod<[string], undefined>,
  'deleteFeeStructure' : ActorMethod<[string], undefined>,
  'deletePayment' : ActorMethod<[string], undefined>,
  'deleteStaff' : ActorMethod<[Identifier], undefined>,
  'deleteStudent' : ActorMethod<[Identifier], undefined>,
  'deleteStudentInvoice' : ActorMethod<[string], undefined>,
  'deleteTeacher' : ActorMethod<[Identifier], undefined>,
  'enrollStudentInClass' : ActorMethod<
    [Identifier, [] | [Identifier]],
    undefined
  >,
  'generatePayroll' : ActorMethod<
    [string, bigint, bigint, bigint, bigint, bigint, bigint],
    string
  >,
  'getActiveLMSCourses' : ActorMethod<[], Array<Course>>,
  'getActiveStaff' : ActorMethod<[], Array<Staff>>,
  'getActiveStudents' : ActorMethod<[], Array<Student>>,
  'getActiveTeachers' : ActorMethod<[], Array<Teacher>>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllApplicants' : ActorMethod<[], Array<Applicant>>,
  'getAllClasses' : ActorMethod<[], Array<Class>>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllDepartments' : ActorMethod<[], Array<Department>>,
  'getAllExpenses' : ActorMethod<[], Array<Expense>>,
  'getAllFeeStructures' : ActorMethod<[], Array<FeeStructure>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAllResourceLinks' : ActorMethod<[], Array<ResourceLink>>,
  'getAllStaff' : ActorMethod<[], Array<Staff>>,
  'getAllStudentInvoices' : ActorMethod<[], Array<StudentInvoice>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllTeachers' : ActorMethod<[], Array<Teacher>>,
  'getAnnouncement' : ActorMethod<[string], Announcement>,
  'getApplicant' : ActorMethod<[string], Applicant>,
  'getApplicantsByStatus' : ActorMethod<[string], Array<Applicant>>,
  'getAssignment' : ActorMethod<[Identifier], Assignment>,
  'getAssignmentsByCourse' : ActorMethod<[CourseId], Array<Assignment>>,
  'getAttendance' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getAttendanceByClassAndDate' : ActorMethod<
    [Identifier, bigint],
    Array<AttendanceRecord>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClass' : ActorMethod<[Identifier], Class>,
  'getCourse' : ActorMethod<[string], Course>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'totalClasses' : bigint,
      'totalStudents' : bigint,
      'totalStaff' : bigint,
      'totalTeachers' : bigint,
      'totalCourses' : bigint,
    }
  >,
  'getDepartment' : ActorMethod<[string], Department>,
  'getExpense' : ActorMethod<[string], Expense>,
  'getFeeStructure' : ActorMethod<[string], FeeStructure>,
  'getGrade' : ActorMethod<[string], GradeRecord>,
  'getGradesByStudent' : ActorMethod<[Identifier], Array<GradeRecord>>,
  'getGradesBySubject' : ActorMethod<[Subject], Array<GradeRecord>>,
  'getLeaveRequest' : ActorMethod<[Identifier], LeaveRequest>,
  'getLeaveRequestsByStaff' : ActorMethod<[string], Array<LeaveRequest>>,
  'getLeaveRequestsByStaffId' : ActorMethod<[string], Array<LeaveRequest>>,
  'getLesson' : ActorMethod<[Identifier], Lesson>,
  'getLessonsByCourse' : ActorMethod<[CourseId], Array<Lesson>>,
  'getOverdueInvoices' : ActorMethod<[], Array<StudentInvoice>>,
  'getPayment' : ActorMethod<[string], Payment>,
  'getPayrollRecord' : ActorMethod<[string], PayrollRecord>,
  'getPayrollRecordsByStaff' : ActorMethod<[string], Array<PayrollRecord>>,
  'getPendingAttendanceCorrections' : ActorMethod<
    [],
    Array<AttendanceCorrection>
  >,
  'getPendingLeaveRequests' : ActorMethod<[], Array<LeaveRequest>>,
  'getResourceLinksByCourse' : ActorMethod<[string], Array<ResourceLink>>,
  'getSalarySlipData' : ActorMethod<[string], [] | [SalarySlipData]>,
  'getSchoolProfile' : ActorMethod<[], SchoolProfile>,
  'getStaff' : ActorMethod<[Identifier], Staff>,
  'getStudent' : ActorMethod<[Identifier], Student>,
  'getStudentInvoice' : ActorMethod<[string], StudentInvoice>,
  'getStudentsSortedByFirstName' : ActorMethod<[], Array<Student>>,
  'getStudentsSortedByLastName' : ActorMethod<[], Array<Student>>,
  'getSubmission' : ActorMethod<[string], AssignmentSubmission>,
  'getSubmissionsByAssignment' : ActorMethod<
    [Identifier],
    Array<AssignmentSubmission>
  >,
  'getSubmissionsByStudent' : ActorMethod<
    [Identifier],
    Array<AssignmentSubmission>
  >,
  'getTeacher' : ActorMethod<[Identifier], Teacher>,
  'getTeacherAttendanceByDate' : ActorMethod<
    [bigint],
    Array<TeacherAttendance>
  >,
  'getTeacherAttendanceByTeacher' : ActorMethod<
    [string],
    Array<TeacherAttendance>
  >,
  'getTotalExpenses' : ActorMethod<[], bigint>,
  'getTotalFeesCollected' : ActorMethod<[], bigint>,
  'getUnpaidInvoices' : ActorMethod<[], Array<StudentInvoice>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'gradeSubmission' : ActorMethod<[string, bigint, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markPayrollAsPaid' : ActorMethod<[string], undefined>,
  'recordAttendance' : ActorMethod<[AttendanceRecordInput], string>,
  'recordGrade' : ActorMethod<
    [Identifier, Subject, Term, Score, Remarks],
    string
  >,
  'rejectAttendanceCorrection' : ActorMethod<[string], undefined>,
  'rejectLeaveRequest' : ActorMethod<[Identifier], undefined>,
  'removeStudentFromClass' : ActorMethod<[Identifier, Identifier], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAssignment' : ActorMethod<[Identifier, Identifier, string], string>,
  'submitAttendanceCorrection' : ActorMethod<
    [string, bigint, string, string],
    string
  >,
  'submitLeaveRequest' : ActorMethod<
    [StaffId, LeaveType, StartDate, EndDate, Reason],
    Identifier
  >,
  'updateApplicant' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      Notes,
    ],
    string
  >,
  'updateApplicantStatus' : ActorMethod<[string, string], undefined>,
  'updateClass' : ActorMethod<
    [Identifier, Name, Identifier, Subjects],
    Identifier
  >,
  'updateExpense' : ActorMethod<
    [string, string, string, bigint, bigint, string],
    string
  >,
  'updateFeeStructure' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      GradeLevel,
      string,
      string,
      string,
      IsActive,
    ],
    string
  >,
  'updatePayment' : ActorMethod<
    [string, string, Identifier, bigint, bigint, string, string],
    string
  >,
  'updateStaff' : ActorMethod<
    [
      Identifier,
      string,
      string,
      Position,
      DepartmentId,
      EmploymentType,
      Salary,
      ContactEmail,
      ContactPhone,
      HireDate,
      IsActive,
    ],
    Identifier
  >,
  'updateStudent' : ActorMethod<
    [
      Identifier,
      string,
      string,
      Grade,
      ContactEmail,
      ContactPhone,
      ParentName,
      EnrollmentDate,
      [] | [bigint],
      IsActive,
    ],
    Identifier
  >,
  'updateStudentInvoice' : ActorMethod<
    [string, Identifier, string, bigint, bigint, string, bigint],
    string
  >,
  'updateTeacher' : ActorMethod<
    [
      Identifier,
      string,
      string,
      Subjects,
      ContactEmail,
      ContactPhone,
      DateOfJoin,
      [] | [string],
      IsActive,
    ],
    Identifier
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];