/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Class {
    id: Identifier;
    subjects: Subjects;
    name: Name;
    teacherId: Identifier;
}
export type ApplicantId = string;
export type GradeLevel = string;
export type MaxScore = bigint;
export type DepartmentId = string;
export interface Teacher {
    id: Identifier;
    subjects: Subjects;
    isActive: IsActive;
    grade?: string;
    contactEmail: ContactEmail;
    lastName: string;
    dateOfJoin: DateOfJoin;
    contactPhone: ContactPhone;
    firstName: string;
}
export interface Lesson {
    id: Identifier;
    title: Title;
    contentText: ContentText;
    courseId: CourseId;
    orderIndex: OrderIndex;
}
export interface StudentInvoice {
    id: string;
    status: string;
    studentId: Identifier;
    feeStructureId: string;
    dueDate: bigint;
    issuedDate: bigint;
    amount: bigint;
}
export type Title = string;
export type EndDate = bigint;
export interface ResourceLink {
    id: string;
    url: string;
    title: string;
    resourceType: string;
    courseId: string;
}
export type DueDate = bigint;
export type CourseId = string;
export interface AttendanceRecord {
    absentStudents: Array<Identifier>;
    date: bigint;
    classId: Identifier;
    presentStudents: Array<Identifier>;
}
export type Identifier = string;
export type Subject = string;
export interface Assignment {
    id: Identifier;
    title: Title;
    maxScore: MaxScore;
    dueDate: DueDate;
    instructions: Instructions;
    courseId: CourseId;
}
export interface Student {
    id: Identifier;
    dob?: bigint;
    isActive: IsActive;
    grade: Grade;
    contactEmail: ContactEmail;
    enrollmentDate: EnrollmentDate;
    lastName: string;
    parentName: ParentName;
    contactPhone: ContactPhone;
    firstName: string;
}
export interface SalarySlipData {
    month: bigint;
    staffId: string;
    year: bigint;
    deductions: bigint;
    netSalary: bigint;
    allowances: bigint;
    basicSalary: bigint;
}
export type ContentText = string;
export type ParentName = string;
export type Score = bigint;
export interface GradeRecord {
    studentId: Identifier;
    subject: Subject;
    term: Term;
    score: Score;
    remarks: Remarks;
}
export type Name = string;
export interface Payment {
    id: string;
    method: string;
    studentId: Identifier;
    invoiceId: string;
    notes: string;
    paymentDate: bigint;
    amount: bigint;
}
export type Notes = string;
export interface Expense {
    id: string;
    date: bigint;
    approvedBy: string;
    description: string;
    category: string;
    amount: bigint;
}
export interface AssignmentSubmission {
    id: string;
    studentId: Identifier;
    submittedAt: bigint;
    feedback?: string;
    isGraded: boolean;
    score?: bigint;
    assignmentId: Identifier;
    submissionText: string;
}
export interface Applicant {
    id: ApplicantId;
    status: string;
    classApplied: string;
    email: string;
    dateApplied: bigint;
    programApplied: string;
    notes: Notes;
    phone: string;
    lastName: string;
    firstName: string;
}
export interface TeacherAttendance {
    id: string;
    status: string;
    date: bigint;
    notes: string;
    teacherId: string;
}
export interface Department {
    id: string;
    name: string;
    description: string;
}
export type Position = string;
export interface AttendanceRecordInput {
    absentStudents: Array<Identifier>;
    date: bigint;
    classId: Identifier;
    presentStudents: Array<Identifier>;
}
export type Term = string;
export interface AttendanceCorrection {
    id: string;
    status: string;
    staffId: string;
    date: bigint;
    requestedStatus: string;
    reason: string;
}
export type IsActive = boolean;
export type AuthorName = string;
export interface UserProfile {
    linkedId?: string;
    name: string;
    role: string;
}
export type Salary = bigint;
export type Timestamp = bigint;
export type StartDate = bigint;
export type LeaveType = string;
export type Remarks = string;
export interface Course {
    id: string;
    title: string;
    subject: string;
    description: string;
    classId: string;
    isActive: boolean;
    teacherId: string;
}
export interface FeeStructure {
    id: FeeId;
    name: string;
    feeType: string;
    description: string;
    isActive: IsActive;
    academicYear: string;
    gradeLevel: GradeLevel;
    feeTypeLabel: string;
    amount: bigint;
}
export type Instructions = string;
export type Grade = bigint;
export type FeeId = string;
export interface LeaveRequest {
    id: Identifier;
    status: Status;
    endDate: EndDate;
    staffId: StaffId;
    leaveType: LeaveType;
    startDate: StartDate;
    reason: Reason;
}
export type OrderIndex = bigint;
export interface Staff {
    id: Identifier;
    salary: Salary;
    hireDate: HireDate;
    isActive: IsActive;
    employmentType: EmploymentType;
    contactEmail: ContactEmail;
    position: Position;
    lastName: string;
    departmentId: DepartmentId;
    contactPhone: ContactPhone;
    firstName: string;
}
export type EnrollmentDate = bigint;
export interface Announcement {
    id: string;
    title: Title;
    body: Body;
    authorName: AuthorName;
    timestamp: Timestamp;
}
export type DateOfJoin = bigint;
export interface SchoolProfile {
    motto: string;
    email: string;
    address: string;
    phone: string;
    schoolName: string;
}
export type ContactPhone = string;
export type StaffId = string;
export type EmploymentType = string;
export interface PayrollRecord {
    id: string;
    month: bigint;
    staffId: string;
    year: bigint;
    deductions: bigint;
    isPaid: boolean;
    netPay: bigint;
    allowances: bigint;
    basicSalary: bigint;
}
export type Body = string;
export type ContactEmail = string;
export type HireDate = bigint;
export type Status = string;
export type Reason = string;
export type Subjects = Array<string>;
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addOrUpdateAssignment(courseId: CourseId, title: Title, instructions: Instructions, dueDate: DueDate, maxScore: MaxScore): Promise<Identifier>;
    addOrUpdateCourse(title: string, description: string, teacherId: string, classId: string, subject: string, isActive: boolean): Promise<string>;
    addOrUpdateDepartment(id: string, name: string, description: string): Promise<string>;
    addOrUpdateLesson(courseId: CourseId, title: Title, contentText: ContentText, orderIndex: OrderIndex): Promise<Identifier>;
    addResourceLink(courseId: string, title: string, url: string, resourceType: string): Promise<string>;
    addTeacherAttendance(teacherId: string, date: bigint, status: string, notes: string): Promise<string>;
    approveAttendanceCorrection(id: string): Promise<void>;
    approveLeaveRequest(leaveRequestId: Identifier): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    convertApplicantToStudent(applicantId: string): Promise<Identifier>;
    createAnnouncement(title: Title, body: Body, authorName: AuthorName): Promise<string>;
    createApplicant(firstName: string, lastName: string, email: string, phone: string, programApplied: string, classApplied: string, dateApplied: bigint, status: string, notes: Notes): Promise<string>;
    createClass(name: Name, teacherId: Identifier, subjects: Subjects): Promise<Identifier>;
    createExpense(category: string, description: string, amount: bigint, date: bigint, approvedBy: string): Promise<string>;
    createFeeStructure(name: string, description: string, amount: bigint, gradeLevel: GradeLevel, academicYear: string, feeType: string, feeTypeLabel: string, isActive: IsActive): Promise<string>;
    createPayment(invoiceId: string, studentId: Identifier, amount: bigint, paymentDate: bigint, method: string, notes: string): Promise<string>;
    createStaff(firstName: string, lastName: string, position: Position, departmentId: DepartmentId, employmentType: EmploymentType, salary: Salary, contactEmail: ContactEmail, contactPhone: ContactPhone, hireDate: HireDate, isActive: IsActive): Promise<Identifier>;
    createStudent(firstName: string, lastName: string, grade: Grade, contactEmail: ContactEmail, contactPhone: ContactPhone, parentName: ParentName, enrollmentDate: EnrollmentDate, dob: bigint | null, isActive: IsActive): Promise<Identifier>;
    createStudentInvoice(studentId: Identifier, feeStructureId: string, amount: bigint, dueDate: bigint, status: string, issuedDate: bigint): Promise<string>;
    createTeacher(firstName: string, lastName: string, subjects: Subjects, contactEmail: ContactEmail, contactPhone: ContactPhone, dateOfJoin: DateOfJoin, grade: string | null, isActive: IsActive): Promise<Identifier>;
    deleteApplicant(id: string): Promise<void>;
    deleteClass(id: Identifier): Promise<void>;
    deleteCourse(id: string): Promise<void>;
    deleteDepartment(id: string): Promise<void>;
    deleteExpense(id: string): Promise<void>;
    deleteFeeStructure(id: string): Promise<void>;
    deletePayment(id: string): Promise<void>;
    deleteStaff(id: Identifier): Promise<void>;
    deleteStudent(id: Identifier): Promise<void>;
    deleteStudentInvoice(id: string): Promise<void>;
    deleteTeacher(id: Identifier): Promise<void>;
    enrollStudentInClass(classId: Identifier, studentId: Identifier | null): Promise<void>;
    generatePayroll(staffId: string, month: bigint, year: bigint, basicSalary: bigint, allowances: bigint, deductions: bigint, netPay: bigint): Promise<string>;
    getActiveLMSCourses(): Promise<Array<Course>>;
    getActiveStaff(): Promise<Array<Staff>>;
    getActiveStudents(): Promise<Array<Student>>;
    getActiveTeachers(): Promise<Array<Teacher>>;
    getAllAnnouncements(): Promise<Array<Announcement>>;
    getAllApplicants(): Promise<Array<Applicant>>;
    getAllClasses(): Promise<Array<Class>>;
    getAllCourses(): Promise<Array<Course>>;
    getAllDepartments(): Promise<Array<Department>>;
    getAllExpenses(): Promise<Array<Expense>>;
    getAllFeeStructures(): Promise<Array<FeeStructure>>;
    getAllPayments(): Promise<Array<Payment>>;
    getAllResourceLinks(): Promise<Array<ResourceLink>>;
    getAllStaff(): Promise<Array<Staff>>;
    getAllStudentInvoices(): Promise<Array<StudentInvoice>>;
    getAllStudents(): Promise<Array<Student>>;
    getAllTeachers(): Promise<Array<Teacher>>;
    getAnnouncement(id: string): Promise<Announcement>;
    getApplicant(id: string): Promise<Applicant>;
    getApplicantsByStatus(status: string): Promise<Array<Applicant>>;
    getAssignment(id: Identifier): Promise<Assignment>;
    getAssignmentsByCourse(courseId: CourseId): Promise<Array<Assignment>>;
    getAttendance(classId: string): Promise<Array<AttendanceRecord>>;
    getAttendanceByClassAndDate(classId: Identifier, date: bigint): Promise<Array<AttendanceRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClass(id: Identifier): Promise<Class>;
    getCourse(id: string): Promise<Course>;
    getDashboardStats(): Promise<{
        totalClasses: bigint;
        totalStudents: bigint;
        totalStaff: bigint;
        totalTeachers: bigint;
        totalCourses: bigint;
    }>;
    getDepartment(id: string): Promise<Department>;
    getExpense(id: string): Promise<Expense>;
    getFeeStructure(id: string): Promise<FeeStructure>;
    getGrade(gradeId: string): Promise<GradeRecord>;
    getGradesByStudent(studentId: Identifier): Promise<Array<GradeRecord>>;
    getGradesBySubject(subject: Subject): Promise<Array<GradeRecord>>;
    getLeaveRequest(id: Identifier): Promise<LeaveRequest>;
    getLeaveRequestsByStaff(staffId: string): Promise<Array<LeaveRequest>>;
    getLeaveRequestsByStaffId(staffId: string): Promise<Array<LeaveRequest>>;
    getLesson(id: Identifier): Promise<Lesson>;
    getLessonsByCourse(courseId: CourseId): Promise<Array<Lesson>>;
    getOverdueInvoices(): Promise<Array<StudentInvoice>>;
    getPayment(id: string): Promise<Payment>;
    getPayrollRecord(id: string): Promise<PayrollRecord>;
    getPayrollRecordsByStaff(staffId: string): Promise<Array<PayrollRecord>>;
    getAllAttendanceCorrections(): Promise<Array<AttendanceCorrection>>;
    getPendingAttendanceCorrections(): Promise<Array<AttendanceCorrection>>;
    getPendingLeaveRequests(): Promise<Array<LeaveRequest>>;
    getResourceLinksByCourse(courseId: string): Promise<Array<ResourceLink>>;
    getSalarySlipData(staffId: string): Promise<SalarySlipData | null>;
    getSchoolProfile(): Promise<SchoolProfile>;
    getStaff(id: Identifier): Promise<Staff>;
    getStudent(id: Identifier): Promise<Student>;
    getStudentInvoice(id: string): Promise<StudentInvoice>;
    getStudentsSortedByFirstName(): Promise<Array<Student>>;
    getStudentsSortedByLastName(): Promise<Array<Student>>;
    getSubmission(id: string): Promise<AssignmentSubmission>;
    getSubmissionsByAssignment(assignmentId: Identifier): Promise<Array<AssignmentSubmission>>;
    getSubmissionsByStudent(studentId: Identifier): Promise<Array<AssignmentSubmission>>;
    getTeacher(id: Identifier): Promise<Teacher>;
    getTeacherAttendanceByDate(date: bigint): Promise<Array<TeacherAttendance>>;
    getTeacherAttendanceByTeacher(teacherId: string): Promise<Array<TeacherAttendance>>;
    getTotalExpenses(): Promise<bigint>;
    getTotalFeesCollected(): Promise<bigint>;
    getUnpaidInvoices(): Promise<Array<StudentInvoice>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    gradeSubmission(submissionId: string, score: bigint, feedback: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    markPayrollAsPaid(payrollId: string): Promise<void>;
    recordAttendance(attendanceInput: AttendanceRecordInput): Promise<string>;
    recordGrade(studentId: Identifier, subject: Subject, term: Term, score: Score, remarks: Remarks): Promise<string>;
    rejectAttendanceCorrection(id: string): Promise<void>;
    rejectLeaveRequest(leaveRequestId: Identifier): Promise<void>;
    removeStudentFromClass(classId: Identifier, studentId: Identifier): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitAssignment(assignmentId: Identifier, studentId: Identifier, submissionText: string): Promise<string>;
    submitAttendanceCorrection(staffId: string, date: bigint, requestedStatus: string, reason: string): Promise<string>;
    submitLeaveRequest(staffId: StaffId, leaveType: LeaveType, startDate: StartDate, endDate: EndDate, reason: Reason): Promise<Identifier>;
    updateApplicant(id: string, firstName: string, lastName: string, email: string, phone: string, programApplied: string, classApplied: string, dateApplied: bigint, status: string, notes: Notes): Promise<string>;
    updateApplicantStatus(id: string, status: string): Promise<void>;
    updateClass(id: Identifier, name: Name, teacherId: Identifier, subjects: Subjects): Promise<Identifier>;
    updateExpense(id: string, category: string, description: string, amount: bigint, date: bigint, approvedBy: string): Promise<string>;
    updateFeeStructure(id: string, name: string, description: string, amount: bigint, gradeLevel: GradeLevel, academicYear: string, feeType: string, feeTypeLabel: string, isActive: IsActive): Promise<string>;
    updatePayment(id: string, invoiceId: string, studentId: Identifier, amount: bigint, paymentDate: bigint, method: string, notes: string): Promise<string>;
    updateStaff(id: Identifier, firstName: string, lastName: string, position: Position, departmentId: DepartmentId, employmentType: EmploymentType, salary: Salary, contactEmail: ContactEmail, contactPhone: ContactPhone, hireDate: HireDate, isActive: IsActive): Promise<Identifier>;
    updateStudent(id: Identifier, firstName: string, lastName: string, grade: Grade, contactEmail: ContactEmail, contactPhone: ContactPhone, parentName: ParentName, enrollmentDate: EnrollmentDate, dob: bigint | null, isActive: IsActive): Promise<Identifier>;
    updateStudentInvoice(id: string, studentId: Identifier, feeStructureId: string, amount: bigint, dueDate: bigint, status: string, issuedDate: bigint): Promise<string>;
    updateTeacher(id: Identifier, firstName: string, lastName: string, subjects: Subjects, contactEmail: ContactEmail, contactPhone: ContactPhone, dateOfJoin: DateOfJoin, grade: string | null, isActive: IsActive): Promise<Identifier>;
    createUserAccount(username: string, password: string, role: string, name: string): Promise<boolean>;
    deleteUserAccount(username: string): Promise<void>;
    getAllUserAccounts(): Promise<Array<{username: string; password: string; role: string; name: string}>>;
    importUserAccounts(accounts: Array<{username: string; password: string; role: string; name: string}>): Promise<bigint>;
    updateUserAccountPassword(username: string, newPassword: string): Promise<boolean>;
    validateUserAccount(username: string, password: string): Promise<{username: string; password: string; role: string; name: string} | null>;
}
import type { AssignmentSubmission as _AssignmentSubmission, ContactEmail as _ContactEmail, ContactPhone as _ContactPhone, DateOfJoin as _DateOfJoin, EnrollmentDate as _EnrollmentDate, Grade as _Grade, Identifier as _Identifier, IsActive as _IsActive, ParentName as _ParentName, SalarySlipData as _SalarySlipData, Student as _Student, Subjects as _Subjects, Teacher as _Teacher, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addOrUpdateAssignment(arg0: CourseId, arg1: Title, arg2: Instructions, arg3: DueDate, arg4: MaxScore): Promise<Identifier> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateAssignment(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateAssignment(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addOrUpdateCourse(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: boolean): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateCourse(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateCourse(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addOrUpdateDepartment(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateDepartment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateDepartment(arg0, arg1, arg2);
            return result;
        }
    }
    async addOrUpdateLesson(arg0: CourseId, arg1: Title, arg2: ContentText, arg3: OrderIndex): Promise<Identifier> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateLesson(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateLesson(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addResourceLink(arg0: string, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addResourceLink(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResourceLink(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addTeacherAttendance(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeacherAttendance(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeacherAttendance(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async approveAttendanceCorrection(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveAttendanceCorrection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveAttendanceCorrection(arg0);
            return result;
        }
    }
    async approveLeaveRequest(arg0: Identifier): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveLeaveRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveLeaveRequest(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async convertApplicantToStudent(arg0: string): Promise<Identifier> {
        if (this.processError) {
            try {
                const result = await this.actor.convertApplicantToStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.convertApplicantToStudent(arg0);
            return result;
        }
    }
    async createAnnouncement(arg0: Title, arg1: Body, arg2: AuthorName): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnnouncement(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnnouncement(arg0, arg1, arg2);
            return result;
        }
    }
    async createApplicant(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint, arg7: string, arg8: Notes): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createApplicant(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createApplicant(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async createClass(arg0: Name, arg1: Identifier, arg2: Subjects): Promise<Identifier> {
        if (this.processError) {
            try {
                const result = await this.actor.createClass(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClass(arg0, arg1, arg2);
            return result;
        }
    }
    async createExpense(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createExpense(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExpense(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createFeeStructure(arg0: string, arg1: string, arg2: bigint, arg3: GradeLevel, arg4: string, arg5: string, arg6: string, arg7: IsActive): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createFeeStructure(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFeeStructure(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async createPayment(arg0: string, arg1: Identifier, arg2: bigint, arg3: bigint, arg4: string, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayment(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayment(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createStaff(arg0: string, arg1: string, arg2: Position, arg3: DepartmentId, arg4: EmploymentType, arg5: Salary, arg6: ContactEmail, arg7: ContactPhone, arg8: HireDate, arg9: IsActive): Promise<Identifier> {
        if (this.processError) {
            try {
                const result = await this.actor.createStaff(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStaff(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async createStudent(arg0: string, arg1: string, arg2: Grade, arg3: ContactEmail, arg4: ContactPhone, arg5: ParentName, arg6: EnrollmentDate, arg7: bigint | null, arg8: IsActive): Promise<Identifier> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg7), arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg7), arg8);
            return result;
        }
    }
    async createStudentInvoice(arg0: Identifier, arg1: string, arg2: bigint, arg3: bigint, arg4: string, arg5: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudentInvoice(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudentInvoice(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createTeacher(arg0: string, arg1: string, arg2: Subjects, arg3: ContactEmail, arg4: ContactPhone, arg5: DateOfJoin, arg6: string | null, arg7: IsActive): Promise<Identifier> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeacher(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeacher(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
    async deleteApplicant(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteApplicant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteApplicant(arg0);
            return result;
        }
    }
    async deleteClass(arg0: Identifier): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClass(arg0);
            return result;
        }
    }
    async deleteCourse(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCourse(arg0);
            return result;
        }
    }
    async deleteDepartment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDepartment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDepartment(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteFeeStructure(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFeeStructure(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFeeStructure(arg0);
            return result;
        }
    }
    async deletePayment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePayment(arg0);
            return result;
        }
    }
    async deleteStaff(arg0: Identifier): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStaff(arg0);
            return result;
        }
    }
    async deleteStudent(arg0: Identifier): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async deleteStudentInvoice(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudentInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudentInvoice(arg0);
            return result;
        }
    }
    async deleteTeacher(arg0: Identifier): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeacher(arg0);
            return result;
        }
    }
    async enrollStudentInClass(arg0: Identifier, arg1: Identifier | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollStudentInClass(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollStudentInClass(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async generatePayroll(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generatePayroll(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generatePayroll(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async getActiveLMSCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveLMSCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveLMSCourses();
            return result;
        }
    }
    async getActiveStaff(): Promise<Array<Staff>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveStaff();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveStaff();
            return result;
        }
    }
    async getActiveStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveStudents();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveStudents();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveTeachers(): Promise<Array<Teacher>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveTeachers();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveTeachers();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnnouncements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnnouncements();
            return result;
        }
    }
    async getAllApplicants(): Promise<Array<Applicant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApplicants();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApplicants();
            return result;
        }
    }
    async getAllClasses(): Promise<Array<Class>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClasses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClasses();
            return result;
        }
    }
    async getAllCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCourses();
            return result;
        }
    }
    async getAllDepartments(): Promise<Array<Department>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDepartments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDepartments();
            return result;
        }
    }
    async getAllExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExpenses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExpenses();
            return result;
        }
    }
    async getAllFeeStructures(): Promise<Array<FeeStructure>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeeStructures();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeeStructures();
            return result;
        }
    }
    async getAllPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return result;
        }
    }
    async getAllResourceLinks(): Promise<Array<ResourceLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResourceLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResourceLinks();
            return result;
        }
    }
    async getAllStaff(): Promise<Array<Staff>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStaff();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStaff();
            return result;
        }
    }
    async getAllStudentInvoices(): Promise<Array<StudentInvoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudentInvoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudentInvoices();
            return result;
        }
    }
    async getAllStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTeachers(): Promise<Array<Teacher>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeachers();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeachers();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnnouncement(arg0: string): Promise<Announcement> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnouncement(arg0);
            return result;
        }
    }
    async getApplicant(arg0: string): Promise<Applicant> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicant(arg0);
            return result;
        }
    }
    async getApplicantsByStatus(arg0: string): Promise<Array<Applicant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicantsByStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicantsByStatus(arg0);
            return result;
        }
    }
    async getAssignment(arg0: Identifier): Promise<Assignment> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignment(arg0);
            return result;
        }
    }
    async getAssignmentsByCourse(arg0: CourseId): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignmentsByCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignmentsByCourse(arg0);
            return result;
        }
    }
    async getAttendance(arg0: string): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendance(arg0);
            return result;
        }
    }
    async getAttendanceByClassAndDate(arg0: Identifier, arg1: bigint): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByClassAndDate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByClassAndDate(arg0, arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClass(arg0: Identifier): Promise<Class> {
        if (this.processError) {
            try {
                const result = await this.actor.getClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClass(arg0);
            return result;
        }
    }
    async getCourse(arg0: string): Promise<Course> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return result;
        }
    }
    async getDashboardStats(): Promise<{
        totalClasses: bigint;
        totalStudents: bigint;
        totalStaff: bigint;
        totalTeachers: bigint;
        totalCourses: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDepartment(arg0: string): Promise<Department> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepartment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepartment(arg0);
            return result;
        }
    }
    async getExpense(arg0: string): Promise<Expense> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpense(arg0);
            return result;
        }
    }
    async getFeeStructure(arg0: string): Promise<FeeStructure> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeeStructure(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeeStructure(arg0);
            return result;
        }
    }
    async getGrade(arg0: string): Promise<GradeRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getGrade(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGrade(arg0);
            return result;
        }
    }
    async getGradesByStudent(arg0: Identifier): Promise<Array<GradeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGradesByStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGradesByStudent(arg0);
            return result;
        }
    }
    async getGradesBySubject(arg0: Subject): Promise<Array<GradeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGradesBySubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGradesBySubject(arg0);
            return result;
        }
    }
    async getLeaveRequest(arg0: Identifier): Promise<LeaveRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaveRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaveRequest(arg0);
            return result;
        }
    }
    async getLeaveRequestsByStaff(arg0: string): Promise<Array<LeaveRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaveRequestsByStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaveRequestsByStaff(arg0);
            return result;
        }
    }
    async getLeaveRequestsByStaffId(arg0: string): Promise<Array<LeaveRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaveRequestsByStaffId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaveRequestsByStaffId(arg0);
            return result;
        }
    }
    async getLesson(arg0: Identifier): Promise<Lesson> {
        if (this.processError) {
            try {
                const result = await this.actor.getLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLesson(arg0);
            return result;
        }
    }
    async getLessonsByCourse(arg0: CourseId): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessonsByCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessonsByCourse(arg0);
            return result;
        }
    }
    async getOverdueInvoices(): Promise<Array<StudentInvoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverdueInvoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverdueInvoices();
            return result;
        }
    }
    async getPayment(arg0: string): Promise<Payment> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return result;
        }
    }
    async getPayrollRecord(arg0: string): Promise<PayrollRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayrollRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayrollRecord(arg0);
            return result;
        }
    }
    async getPayrollRecordsByStaff(arg0: string): Promise<Array<PayrollRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayrollRecordsByStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayrollRecordsByStaff(arg0);
            return result;
        }
    }
    async getAllAttendanceCorrections(): Promise<Array<AttendanceCorrection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAttendanceCorrections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAttendanceCorrections();
            return result;
        }
    }
    async getPendingAttendanceCorrections(): Promise<Array<AttendanceCorrection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingAttendanceCorrections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingAttendanceCorrections();
            return result;
        }
    }
    async getPendingLeaveRequests(): Promise<Array<LeaveRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingLeaveRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingLeaveRequests();
            return result;
        }
    }
    async getResourceLinksByCourse(arg0: string): Promise<Array<ResourceLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResourceLinksByCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResourceLinksByCourse(arg0);
            return result;
        }
    }
    async getSalarySlipData(arg0: string): Promise<SalarySlipData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalarySlipData(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalarySlipData(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSchoolProfile(): Promise<SchoolProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getSchoolProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSchoolProfile();
            return result;
        }
    }
    async getStaff(arg0: Identifier): Promise<Staff> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaff(arg0);
            return result;
        }
    }
    async getStudent(arg0: Identifier): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_Student_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_Student_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentInvoice(arg0: string): Promise<StudentInvoice> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentInvoice(arg0);
            return result;
        }
    }
    async getStudentsSortedByFirstName(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsSortedByFirstName();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentsSortedByFirstName();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentsSortedByLastName(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsSortedByLastName();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentsSortedByLastName();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmission(arg0: string): Promise<AssignmentSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmission(arg0);
                return from_candid_AssignmentSubmission_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmission(arg0);
            return from_candid_AssignmentSubmission_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmissionsByAssignment(arg0: Identifier): Promise<Array<AssignmentSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionsByAssignment(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionsByAssignment(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmissionsByStudent(arg0: Identifier): Promise<Array<AssignmentSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionsByStudent(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionsByStudent(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeacher(arg0: Identifier): Promise<Teacher> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacher(arg0);
                return from_candid_Teacher_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacher(arg0);
            return from_candid_Teacher_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeacherAttendanceByDate(arg0: bigint): Promise<Array<TeacherAttendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacherAttendanceByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacherAttendanceByDate(arg0);
            return result;
        }
    }
    async getTeacherAttendanceByTeacher(arg0: string): Promise<Array<TeacherAttendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacherAttendanceByTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacherAttendanceByTeacher(arg0);
            return result;
        }
    }
    async getTotalExpenses(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalExpenses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalExpenses();
            return result;
        }
    }
    async getTotalFeesCollected(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalFeesCollected();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalFeesCollected();
            return result;
        }
    }
    async getUnpaidInvoices(): Promise<Array<StudentInvoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnpaidInvoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnpaidInvoices();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async gradeSubmission(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.gradeSubmission(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gradeSubmission(arg0, arg1, arg2);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markPayrollAsPaid(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markPayrollAsPaid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPayrollAsPaid(arg0);
            return result;
        }
    }
    async recordAttendance(arg0: AttendanceRecordInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAttendance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAttendance(arg0);
            return result;
        }
    }
    async recordGrade(arg0: Identifier, arg1: Subject, arg2: Term, arg3: Score, arg4: Remarks): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.recordGrade(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordGrade(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async rejectAttendanceCorrection(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectAttendanceCorrection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectAttendanceCorrection(arg0);
            return result;
        }
    }
    async rejectLeaveRequest(arg0: Identifier): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectLeaveRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectLeaveRequest(arg0);
            return result;
        }
    }
    async removeStudentFromClass(arg0: Identifier, arg1: Identifier): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeStudentFromClass(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeStudentFromClass(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitAssignment(arg0: Identifier, arg1: Identifier, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAssignment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAssignment(arg0, arg1, arg2);
            return result;
        }
    }
    async submitAttendanceCorrection(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAttendanceCorrection(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAttendanceCorrection(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitLeaveRequest(arg0: StaffId, arg1: LeaveType, arg2: StartDate, arg3: EndDate, arg4: Reason): Promise<Identifier> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLeaveRequest(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLeaveRequest(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateApplicant(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: bigint, arg8: string, arg9: Notes): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplicant(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplicant(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async updateApplicantStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplicantStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplicantStatus(arg0, arg1);
            return result;
        }
    }
    async updateClass(arg0: Identifier, arg1: Name, arg2: Identifier, arg3: Subjects): Promise<Identifier> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClass(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClass(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateExpense(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateFeeStructure(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: GradeLevel, arg5: string, arg6: string, arg7: string, arg8: IsActive): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFeeStructure(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFeeStructure(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updatePayment(arg0: string, arg1: string, arg2: Identifier, arg3: bigint, arg4: bigint, arg5: string, arg6: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayment(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayment(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateStaff(arg0: Identifier, arg1: string, arg2: string, arg3: Position, arg4: DepartmentId, arg5: EmploymentType, arg6: Salary, arg7: ContactEmail, arg8: ContactPhone, arg9: HireDate, arg10: IsActive): Promise<Identifier> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaff(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaff(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async updateStudent(arg0: Identifier, arg1: string, arg2: string, arg3: Grade, arg4: ContactEmail, arg5: ContactPhone, arg6: ParentName, arg7: EnrollmentDate, arg8: bigint | null, arg9: IsActive): Promise<Identifier> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg8), arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg8), arg9);
            return result;
        }
    }
    async updateStudentInvoice(arg0: string, arg1: Identifier, arg2: string, arg3: bigint, arg4: bigint, arg5: string, arg6: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudentInvoice(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudentInvoice(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateTeacher(arg0: Identifier, arg1: string, arg2: string, arg3: Subjects, arg4: ContactEmail, arg5: ContactPhone, arg6: DateOfJoin, arg7: string | null, arg8: IsActive): Promise<Identifier> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeacher(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg7), arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeacher(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg7), arg8);
            return result;
        }
    }
    async createUserAccount(username, password, role, name) {
        const result = await this.actor.createUserAccount(username, password, role, name);
        return result;
    }
    async deleteUserAccount(username) {
        return this.actor.deleteUserAccount(username);
    }
    async getAllUserAccounts() {
        const result = await this.actor.getAllUserAccounts();
        return result;
    }
    async importUserAccounts(accounts) {
        const result = await this.actor.importUserAccounts(accounts);
        return result;
    }
    async updateUserAccountPassword(username, newPassword) {
        const result = await this.actor.updateUserAccountPassword(username, newPassword);
        return result;
    }
    async validateUserAccount(username, password) {
        const result = await this.actor.validateUserAccount(username, password);
        if (result && result.length > 0) return result[0];
        return null;
    }
}
function from_candid_AssignmentSubmission_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssignmentSubmission): AssignmentSubmission {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Teacher_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Teacher): Teacher {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SalarySlipData]): SalarySlipData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Identifier;
    subjects: _Subjects;
    isActive: _IsActive;
    grade: [] | [string];
    contactEmail: _ContactEmail;
    lastName: string;
    dateOfJoin: _DateOfJoin;
    contactPhone: _ContactPhone;
    firstName: string;
}): {
    id: Identifier;
    subjects: Subjects;
    isActive: IsActive;
    grade?: string;
    contactEmail: ContactEmail;
    lastName: string;
    dateOfJoin: DateOfJoin;
    contactPhone: ContactPhone;
    firstName: string;
} {
    return {
        id: value.id,
        subjects: value.subjects,
        isActive: value.isActive,
        grade: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.grade)),
        contactEmail: value.contactEmail,
        lastName: value.lastName,
        dateOfJoin: value.dateOfJoin,
        contactPhone: value.contactPhone,
        firstName: value.firstName
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    linkedId: [] | [string];
    name: string;
    role: string;
}): {
    linkedId?: string;
    name: string;
    role: string;
} {
    return {
        linkedId: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.linkedId)),
        name: value.name,
        role: value.role
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    studentId: _Identifier;
    submittedAt: bigint;
    feedback: [] | [string];
    isGraded: boolean;
    score: [] | [bigint];
    assignmentId: _Identifier;
    submissionText: string;
}): {
    id: string;
    studentId: Identifier;
    submittedAt: bigint;
    feedback?: string;
    isGraded: boolean;
    score?: bigint;
    assignmentId: Identifier;
    submissionText: string;
} {
    return {
        id: value.id,
        studentId: value.studentId,
        submittedAt: value.submittedAt,
        feedback: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.feedback)),
        isGraded: value.isGraded,
        score: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.score)),
        assignmentId: value.assignmentId,
        submissionText: value.submissionText
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Identifier;
    dob: [] | [bigint];
    isActive: _IsActive;
    grade: _Grade;
    contactEmail: _ContactEmail;
    enrollmentDate: _EnrollmentDate;
    lastName: string;
    parentName: _ParentName;
    contactPhone: _ContactPhone;
    firstName: string;
}): {
    id: Identifier;
    dob?: bigint;
    isActive: IsActive;
    grade: Grade;
    contactEmail: ContactEmail;
    enrollmentDate: EnrollmentDate;
    lastName: string;
    parentName: ParentName;
    contactPhone: ContactPhone;
    firstName: string;
} {
    return {
        id: value.id,
        dob: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.dob)),
        isActive: value.isActive,
        grade: value.grade,
        contactEmail: value.contactEmail,
        enrollmentDate: value.enrollmentDate,
        lastName: value.lastName,
        parentName: value.parentName,
        contactPhone: value.contactPhone,
        firstName: value.firstName
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Teacher>): Array<Teacher> {
    return value.map((x)=>from_candid_Teacher_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AssignmentSubmission>): Array<AssignmentSubmission> {
    return value.map((x)=>from_candid_AssignmentSubmission_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Array<Student> {
    return value.map((x)=>from_candid_Student_n7(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Identifier | null): [] | [_Identifier] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    linkedId?: string;
    name: string;
    role: string;
}): {
    linkedId: [] | [string];
    name: string;
    role: string;
} {
    return {
        linkedId: value.linkedId ? candid_some(value.linkedId) : candid_none(),
        name: value.name,
        role: value.role
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
